version: '3.8'

services:
  # mysql
  # database:
  #   container_name: database
  #   image: mysql:8.0
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: project
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - '4306:3306'
  #   volumes:
  #     - ./mysql:/var/lib/mysql

  # postgres
  database:
    container_name: database
    image: postgres:15
    environment:
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DATABASE: project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5430:5432'
    volumes:
      - ./postgres:/var/lib/postgres
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./project:/var/www/project
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./project:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database